project_id = "bkhdorwhekifuapiisxk"

[functions.analyze-video]
verify_jwt = false

[functions.video-chat]
verify_jwt = false

[functions.generate-captions]
verify_jwt = false

[functions.analyze-context]
verify_jwt = false

[functions.generate-storyboard]
verify_jwt = false

[functions.analyze-enhancements]
verify_jwt = false

[functions.generate-enhancement-image]
verify_jwt = false

[functions.generate-enhancement-sfx]
verify_jwt = false
